### ISSUE TITLE
Browser will not open on linux KDE google-chrome

### ISSUE THREAD

**Issue by jamesruan** [xavierchow/vim-sequence-diagram#5]
When I press the <leader>+'\', the files are generated in 'file:///tmp/vim-js-seq' (which takes me a while to find), but the HTML file is not open automatically as expected.

I'm on linux, and using google-chrome on KDE as my main browser.

**Comment by xavierchow** [comment]
Actually the browser is launched by the script [here](https://github.com/xavierchow/vim-sequence-diagram/blob/master/autoload/vim_seq_diag.vim#L34-L38), I'm not familiar with KDE, what happens if you run the command `open /tmp/vim-js-seq/out.html`?
Anyway all you need is a way to open your browser from script, and pull request is welcome.

**Comment by jamesruan** [comment]
After a little googling, I found the xdg-open is the right way to do that.
It tested to be OK on my machine
#6

**Comment by xavierchow** [comment]
Closing.
