### ISSUE TITLE
Trailing characters when running GenerateDiagram

### ISSUE THREAD

**Issue by ghost** [xavierchow/vim-sequence-diagram#7]
I have copied the example from https://bramp.github.io/js-sequence-diagrams/ and tried to run `:<plug>GenerateDiagram` but it's failing with `E488: Trailing characters`.

I'm sure it used to work, but it doesn't seem to now.

**Comment by xavierchow** [comment]
There are a few examples there https://bramp.github.io/js-sequence-diagrams/, which one did you try?

**Comment by ghost** [comment]
The first one

    Andrew->China: Says Hello
    Note right of China: China thinks\nabout it
    China-->Andrew: How are you?
    Andrew->>China: I am good thanks!

But I can't get any to work.

**Comment by xavierchow** [comment]
Just realized you tried with `:<Plug>GenerateDiagram`, this won't work, because as defined [here](https://github.com/xavierchow/vim-sequence-diagram/blob/master/plugin/vim-sequence-diagram.vim#L18) it's a normal mode map, but when you press `:` you're entering command-line mode, they are totally different, check `:help map-modes` for details.
Please use the normal map key binding, see: https://github.com/xavierchow/vim-sequence-diagram#keymap-for-preview

**Comment by ghost** [comment]
Thanks for the update but I'm still not getting anywhere. I may be missing something else but now I don't get the error or the webpage. Where is the rendered file supposed to be? There's nothing written to /tmp.

Thanks again  for your help.

**Comment by xavierchow** [comment]
Normally these html/js files below should be in the `/tmp/vim-js-seq/`, can you let me what's inside the `vim-js-seq` folder?
```
browser.min.js
out.html
raphael-min.js
sequence-diagram-min.js
underscore-min.js
```

**Comment by ghost** [comment]
That directory is not created at all.

**Comment by ghost** [comment]
I take it all back. This was user error on my part with my vim-plug settings. I had mixed up the file extension and filetype in the lazy loading for the plugin so the plugin wasn't loading. I'm surprised vim didn't give an error though.

Thanks for this plugin (and sorry for doubting it).
